version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-9091}:9091
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8080}
    restart: always
